package uz.cluster.db.entity.references.model;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Type;
import org.hibernate.envers.Audited;
import org.hibernate.envers.RelationTargetAuditMode;
import uz.cluster.db.model.Auditable;

import javax.persistence.*;
import java.util.UUID;

@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@Entity
@Audited(targetAuditMode = RelationTargetAuditMode.AUDITED)
@Table(name = "attachment")
public class Attachment extends Auditable {
    @Id
    @GeneratedValue(generator = "uuid2")
    @Type(type = "org.hibernate.type.PostgresUUIDType")
    @GenericGenerator(name = "uuid2", strategy = "org.hibernate.id.UUIDGenerator")
    private UUID id; //Generated By System

    private String originalFileName; // original name of file that uploaded to system

    private long size; //File size

    private String contentType; // Type of content

    private String name; // Name of file given to uploaded file

    @Column(name = "cluster_id", columnDefinition = " real default 1 ", insertable = true, updatable = false)
    private int clusterId = 1;
}
